version: "3.7"

services:
  app:
    image: devvictorpersike/appminhapagina
    container_name: appminhapagina
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`victorpersike.dev.br`)"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "traefik.docker.network=web"

networks:
  web:
    external: true
