name: Deploy to Oracle VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Fazer checkout do repositório
      - name: Check out repository
        uses: actions/checkout@v3

      # 2) Set up Docker Buildx (para build avançado e cache)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3) Login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4) Buildar e enviar (push) a imagem para o Docker Hub
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: '{{defaultContext}}'
          push: true
          tags: |
            devvictorpersike/appminhapagina:latest
            devvictorpersike/appminhapagina:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 5) Preparar SSH (criar ~/.ssh/id_rsa, permissões, known_hosts)
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_RSA_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      # 6) Testar a conexão SSH (opcional mas recomendado)
      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no "${{ secrets.SSH_USER }}"@"${{ secrets.SSH_HOST }}" "echo 'SSH connection successful'"

      # 7) Copiar docker-compose.yml para a VM (substituir o antigo)
      - name: Copy docker-compose.yml
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_RSA_PRIVATE_KEY }}
          source: "deploy/docker-compose.yml"
          target: "/home/ubuntu/frontends/"

      # 8) Executar no servidor: docker compose pull/up
      - name: Deploy on Oracle VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_RSA_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/frontends/deploy/
            docker compose pull
            docker compose up -d
